server:
  port: 8082

spring:
  application:
    name: department-service

  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/department_db

  config:
    import: optional:configserver:http://localhost:8181  # ✅ Ensures config server loads before anything else

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: hr-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# ✅ Swagger Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  paths-to-match: /api/**
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# ✅ Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# ✅ Actuator & Tracing
management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# ✅ Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      departmentServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

# ✅ Logging Configuration
logging:
  level:
    root: info
    com.example: debug
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"

